#
# Round button
#
- alias: 'Button Goodnight'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.button3
      from: 'off'
      to: 'on'
  condition: 
  action:
    - service: script.goodnight

- alias: 'Button Lights'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.button1
      to: 'on'
  condition: 
  action:
    - service: scene.turn_on
      entity_id: scene.morning_lights
    - service: homeassistant.turn_on
      entity_id: switch.switch_3 

- alias: 'Button Lights All off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.button4
      from: 'off'
      to: 'on'
  condition: 
  action:
    - service: scene.turn_on
      entity_id: scene.All_Lights_Off

- alias: 'Button Lights Bright'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.button2
      from: 'off'
      to: 'on'
  condition: 
  action:
    - service: scene.turn_on
      entity_id: scene.Evening_Bright_Lights
