- alias: Waste Container Warning
  initial_state: 'on'
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    condition: template
    value_template: >-
      {%- if (as_timestamp(now()) > (as_timestamp(states.calendar.afvalkalender.attributes.start_time) - 86400)) -%}
        true
      {%- endif -%}
  action:
    - service: notify.family
      data:
        message: "[INFO] Do not forget to take out the {{ states.calendar.afvalkalender.attributes.description }}!"

#
# Alert: Critical Device Offline
# Condition: Once an Hour
#
- alias: 'Notify - Critical Device Offline'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:  sensor.synology_online
      from: 'Online'
      to: 'Offline'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
          {% if states.automation.notify__critical_device_offline.last_triggered is not none %}
            {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.notify__critical_device_offline.attributes.last_triggered) | int > 3600 %} true {% else %} false
            {% endif %}
          {% else %}
          false
          {% endif %}
  action:
    service: notify.ios_iphone_van_michiel
    data:
      title: "System Message"
      message: "{{ trigger.to_state.attributes.friendly_name }} has gone offline. Check status to restore functionality."

# #
# # HA Pi Disk Use Gets Above 65%
# - alias: 'Notify - HA Pi Disk Use'
#   trigger:
#     platform: numeric_state
#     entity_id: sensor.disk_use__2
#     above: 65
#   action:
#     service: notify.ios_iphone_van_michiel
#     data:
#       title: "System Warning"
#       message: "HomeAssistant Disk Space is Low"
      
# - alias: 'Notify -  HA Pi Disk Use Critical'
#   trigger:
#     platform: numeric_state
#     entity_id: sensor.disk_use__2
#     above: 90
#   action:
#     service: notify.ios_iphone_van_michiel
#     data:
#       title: "System Warning"
#       message: "HomeAssistant Disk Space is CRITICALLY Low"

#
# NEW HA Release
- alias: 'Notify - New Home Assistant'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.ios_iphone_van_michiel
    data:
      title: "System Message"
      message: "Home Assistant {{ states.updater.updater.state }} is now available."