################################################
## Automation
################################################

- alias: 'Notify if Nest Protect is in an emergency state'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
      - sensor.upstairs_nest_protect_co_status
      - sensor.upstairs_nest_protect_smoke_status
    to: 'Emergency'
  action:
  - service: notify.family
    data_template:
      title: 'Emergency'
      message: "An emergency has been detected on {{ trigger.to_state.attributes.friendly_name }}!"

- alias: 'Notify if Nest Protect is offline'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.upstairs_nest_protect_online
    from: 'on'
  action:
  - service: notify.family
    data_template:
      title: 'Emergency'
      message: "The {{ trigger.to_state.attributes.friendly_name }} is now {{ (trigger.to_state.state)|replace('_', ' ') }}!"

# Smoke alert: Livingroom
- alias: 'Smoke Alert Livingroom'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.fibaro_smoke_livingroom_alarm_level
    to: '255'
  action:
  - service: notify.notify
    data:
        message: "Fire detected in Livingroom"
        title: "Fire!"
 
        
# TamperAlert Livingroom
- alias: 'Smoke Alarm Tamper Livingroom'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.fibaro_smoke_livingroom_burglar
    to: '3'
  action:
  - service: notify.ios_iphone_van_michiel
    data:
        message: "Smokedetector livingroom not mounted"
        title: "Smokedetector"      

# Smoke alert: Babyroom
- alias: 'Smoke Alert Babyroom'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.fibaro_smoke_babyroom_alarm_level
    to: '255'
  action:
  - service: notify.notify
    data:
        message: "Fire detected in Babyroom"
        title: "Fire!"
 
        
# TamperAlert Babyroom
- alias: 'Smoke Alarm Tamper Babyroom'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.fibaro_smoke_babyrom_burglar
    to: '3'
  action:
  - service: notify.ios_iphone_van_michiel
    data:
        message: "Smokedetector babyroom not mounted"
        title: "Smokedetector"      

# Smoke alert: Kitchen
- alias: 'Smoke Alert Kitchen'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.fibaro_smoke_kitchen_alarm_level
    to: '255'
  action:
  - service: notify.notify
    data:
        message: "Fire detected in Kitchen"
        title: "Fire!"
 
        
# TamperAlert Kitchen
- alias: 'Smoke Alarm Tamper Kitchen'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.fibaro_smoke_kitchen_burglar
    to: '3'
  action:
  - service: notify.ios_iphone_van_michiel
    data:
        message: "Smokedetector kitchen not mounted"
        title: "Smokedetector"      